# GitHub Actions CI/CD Workflow
# This workflow runs on every push to master and on pull requests
# It performs linting, type checking, unit tests, and builds the application

name: CI

# Trigger conditions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define environment variables (optional, can be expanded as needed)
env:
  NODE_VERSION: "18"

jobs:
  # Job 1: Test
  # Runs linting, type checking, and unit tests
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js with the specified version
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install pnpm package manager
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # Get the pnpm store directory path for caching (improves performance)
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Cache pnpm dependencies to speed up subsequent runs
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install dependencies in the app directory
      - name: Install dependencies
        run: pnpm install
        working-directory: ./app

      # Run ESLint and other linting tools
      - name: Run lint
        run: pnpm lint
        working-directory: ./app

      # Run TypeScript type checking
      - name: Run type check
        run: pnpm type-check
        working-directory: ./app

      # Run unit tests
      - name: Run unit tests
        run: pnpm test
        working-directory: ./app

  # Job 2: Build
  # Builds the application (only runs after test job succeeds)
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test  # This job depends on the test job completing successfully

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js with the specified version
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install pnpm package manager
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # Get the pnpm store directory path for caching
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Cache pnpm dependencies to speed up subsequent runs
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install
        working-directory: ./app

      # Build the application
      - name: Build app
        run: pnpm build
        working-directory: ./app
